In [4]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

addition = a + b

print(addition)

subs = a - b
print(subs)

mult = a * b
print(mult)

div = a / b
print(div)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


2D Array

In [ ]:
a2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
b2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

addition = a2 + b2
print(addition)
print("--------------------------")

subs = a2 - b2
print(subs)
print("--------------------------")

mult = a2 * b2 # cell wise multiplication - not matrix multiplication
print(mult)
print("--------------------------")

#matrix multiplication
prod = a2 @ b2
print(prod)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
--------------------------
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
--------------------------
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
--------------------------
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


**Determinant of a matrix**

In [1]:
import numpy as np

a2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

det_a = np.linalg.det(a2)
print(det_a)

-4.263256414560599e-12
