In [ ]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

**Square Root**

In [ ]:
print(np.sqrt(16))

4.0


**Square root of all elements of an array**

In [ ]:
a = np.array([10,20,30,40,50])
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [ ]:
print(a)
print(b)
print("-----------------")
print(np.cumulative_sum(a)) # prefix sum
print(np.cumulative_prod(b))

[10 20 30 40 50]
[1 2 3 4 5]
-----------------
[ 10  30  60 100 150]
[  1   2   6  24 120]
