mean of an array

In [4]:
import numpy as np

arr = np.array([6,4])

print(np.mean(arr))

5.0


mean of a 2D array (matrix)

In [ ]:
matrix = np.random.randint(1,20,(3,4))
print(matrix)

# row wise mean

meanRow = np.mean(matrix, axis = 1)
print(meanRow)

# column wise mean
meanCol = np.mean(matrix, axis = 0)
print(meanCol)

[[10 19  1 11]
 [ 9 10 12 11]
 [ 3 12  8  8]]
[10.25 10.5   7.75]
[ 7.33333333 13.66666667  7.         10.        ]
