In [ ]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
a2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
b2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

Trigonometry

In [ ]:
print(a2)
print("***************")
print(b2)
print("======================")

all_sin_val = np.sin(a) # all values of a are treated as radian, not degree
# so, sin(90) will not be 1, sin(30) will not be 0.5
print(all_sin_val)

print(np.sin(30)) # 30 is treated as radian, not degree

[[10 20 30]
 [40 50 60]
 [70 80 90]]
***************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
-0.9880316240928618


**Radian to Degree**

In [ ]:
a_degree = np.rad2deg(a)

print(a_degree)

a_sin = np.sin(a_degree)
print(a_sin)

[ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]
[ 0.92759846  0.6930622  -0.4097718  -0.99922629 -0.33680768]


**Degree to Radian** </br>
*If we want to treat 90,30,60 etc. as degree, use deg2rad*

In [ ]:

deg_90 = np.deg2rad(90)
print(np.sin(deg_90)) # 1

print(np.sin(np.deg2rad(30))) # 0.5
print(1/(np.sin(np.deg2rad(30)))) # 2, sin(30) = 1/2, so cosec(30) = 2

1.0
0.49999999999999994
2.0000000000000004


In [ ]:
print((np.sqrt(3)))
print(np.tan(np.deg2rad(60))) # sqrt(3) = 1.732
print(1/np.tan(np.deg2rad(60))) # 1/sqrt(3) = 0.57735

1.7320508075688772
1.7320508075688767
0.577350269189626


In [ ]:
print(np.tan(np.deg2rad(30))) # tan(30) = 1/sqrt(3) = 0.57735

0.5773502691896257
