**1D Array Slicing**

*array[start_index : end_index(exclusive) : step]*

In [ ]:
import numpy as np

nums = np.array([10,20,30,40,50,60])

arr = nums[1:4] # index 1 theke 4 er ag porjonto
print(arr)

arr = nums[3:] # index 3 theke baki ja ase sob
print(arr)

arr = nums[0:5:2] # index 0 theke index 5 er ag porjonto, 2 ta kore step niye
print(arr)

arr = nums[::2] # just 2 ta kore step niye, index 0 theke start hobe
print(arr)

rev_arr = nums[::-1] # reverse iteration
print(rev_arr)

[20 30 40]
[40 50 60]
[10 30 50]
[10 30 50]
[60 50 40 30 20 10]


**2D Array Slicing**

*[row_slice, column_slice]*

In [5]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

#get a single row
arr = arr2[1] # row of index 1-->  [4 5 6]
print(arr)

#get a single column
arr = arr2[:,1] # column of index 1 --> [2 5 8]
print(arr)

[4 5 6]
[2 5 8]


Sub matrix --> *[row_slice, column_slice]*

In [13]:
# submatrix
print(arr2)
print("---------------")
# row from index 0 to 1(not 2), colum from index 1 to 2 (not 3)
sub_matrix = arr2[0:2,1:3] 

print(sub_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[2 3]
 [5 6]]


In [14]:
print(arr2)
print("---------------")
r = arr2[0:2,1] 
# row index 0 theke 1 porjonto, tarpor ja baki thakbe, sekhan theke index 1 column
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[2 5]


**Step slicing** </br>
*':' means all* </br>
if it is in row's place, means --> all rows</br>
if it is in columns's place, means --> all columns

In [ ]:
print(arr2)
print("---------------")
step_sliced = arr2[:,::2] # every row, every 2nd column(2 ta kore step)
print(step_sliced)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[1 3]
 [4 6]
 [7 9]]


**':' means "all"**

In [9]:
print(arr2)
print("---------------")
print(arr2[:,1]) # all rows, column 1(idx)..as a 1D array
print("--------------->>")
print(arr2[::,1]) # same as the one above,,all rows, column 1(idx)..as a 1D array
print("--------------->>")
print(arr2[1,:]) # row 1(idx), all columns...as a 1D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[2 5 8]
--------------->>
[2 5 8]
--------------->>
[4 5 6]


In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a[:,:1]) # all rows, columns from index 0 up to 1(not including)
# it will stay as a column matrix

print("++++++++++++++++++++++++++++")

print(a[::,:1]) # same as the previous one

[[1]
 [4]
 [7]]
++++++++++++++++++++++++++++
[[1]
 [4]
 [7]]


arr[:, :1]  --> works like column vector, keeps dimension</br>
arr[:, 1]  --> behaves like flat array, removed dimension

The index is relative to the slice,
but the data lives in the original array. Sliced part is just a view of the original array, so any changes made to the sliced array, changes it to the original array

- NumPy slicing = view (same memory)</br>
- Python slicing = copy (new memory)

In [17]:
arr = np.array([1,2,3,4])
slice_arr = arr[1:3]
print(f"slice_arr = {slice_arr}")

slice_arr[0] = 99
print(arr)

slice_arr = [2 3]
[ 1 99  3  4]


slice_arr = arr[1:3].copy() --> this gives seperate array of the sliced portion, otherwise sliced part is just a view of the original array, so any changes made to the sliced array, changes it to the original array

In [ ]:
arr = np.array([1,2,3,4])
slice_arr = arr[1:3].copy() #* now its a copy, not just view

slice_arr[0] = 99

print(arr)

[1 2 3 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr[1:4] = 0; # changes directly on the original array, because sliced part is just a view by default

print(arr)     

[1 0 0 0 5]
