### **ndArray**

In [25]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

# 2D array
arr2 = np.array([
            [1,2,3],
            [5,6,2],
            [7,8,6],
            [6,3,1]
        ])

print(arr1)
print(f"Dimension of arr1 = {arr1.ndim}")
print(f"Shape of the arr1 (1D): {arr1.shape}")
print(f"Size of the arr1 = ", arr1.size) # total number of elements
print(f"Data type: {arr1.dtype}") # type of the data (data must be homogenous in numpy array)
print("---------------------")
print(arr2)
print(f"Dimension of arr2 = {arr2.ndim}")
print(f"Shape of the arr2 (2D): {arr2.shape}")
print(f"Size of the arr2 = ", arr2.size) # total number of elements
print(f"Data type: {arr2.dtype}") # type of the data (data must be homogenous in numpy array)
print("---------------------")


[1 2 3 4 5]
Dimension of arr1 = 1
Shape of the arr1 (1D): (5,)
Size of the arr1 =  5
Data type: int64
---------------------
[[1 2 3]
 [5 6 2]
 [7 8 6]
 [6 3 1]]
Dimension of arr2 = 2
Shape of the arr2 (2D): (4, 3)
Size of the arr2 =  12
Data type: int64
---------------------


In [ ]:
import numpy as np

arr2 = np.array([
            [1,2,3],
            [5,6,2],
            [7,8,6],
            [6,3,1]
        ])

# just matrix
for row in arr2:
    for col in row:
        print(col,end=" ")
    print()

1 2 3 
5 6 2 
7 8 6 
6 3 1 


### *In a 2D NumPy array:*

- Every row must have the same number of columns
- The structure must be rectangular (not jagged)

For 'shape', returns a tuple, first value is how many rows there are, 2nd value is the number of items(columns) each row has.
However, for 1D array, there is only one value and it is just the size of the array

### **3D Array**

**Characteristics:**
*In a NumPy 3D array, every row must have the same number of columns (and every matrix must have the same shape)*

- Every matrix has the same number of rows
- Every row has the same number of columns

In [24]:
# 3D array
arr3 = np.array([
    [
        [5,3,6,1],[5,3,1,9],[7,3,9,8]
    ],
    [
        [4,2,5,1],[3,6,4,5],[3,1,6,4]
    ],
    # [
    #     [6,2,3,1],[3,7,6,5],[1,5,9,4]
    # ]
])

# print(arr3)
print(f"Dimension of arr3 = {arr3.ndim}")
print(f"Shape of the arr3 (3D): {arr3.shape}")
print(f"Size of the arr3 = ", arr3.size) # total number of elements
print(f"Data type: {arr2.dtype}") # type of the data (data must be homogenous in numpy array)


Dimension of arr3 = 3
Shape of the arr3 (3D): (2, 3, 4)
Size of the arr3 =  24
Data type: int64


*-About the Shape of a 3D Array-*

There are 3 values in the returned tuple. 
1. Number 2D matrix
2. Number rows in each matrix
3. Number columns in each row

**Iterating a 3D array**

In [21]:
arr_3d = np.array([
    [
        [5,3,6,1],[5,3,1,9],[7,3,9,8]
    ],
    [
        [4,2,5,1],[3,6,4,5],[3,1,6,4]
    ],
    # [
    #     [6,2,3,1],[3,7,6,5],[1,5,9,4]
    # ]
])

for matrix in arr_3d:
    for row in matrix:
        for value in row:
            print(value,end=" ")
        print()
    print()

5 3 6 1 
5 3 1 9 
7 3 9 8 

4 2 5 1 
3 6 4 5 
3 1 6 4 



In [23]:
arr = np.arange(24).reshape(2, 3, 4)

print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [1]:
import numpy as np
arr_eye = np.eye(3)

print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
arr = np.full((4,3), np.inf)
print(arr)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [2]:
import numpy as np
print(np.__version__)

2.4.4


In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr