2D Array

In [2]:
import numpy as np

arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr2[1][2])

6


In [ ]:
import numpy as np

arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr2[[1,1],[1,2]])
# [1,1] -> value of row 1 and column 1
# [1,2] -> value of row 1 and column 2

[5 6]


#### with boolean filtering condition

In [ ]:
print(arr2)
print("---------------")

print(arr2[arr2<4])
print(arr2[arr2%2 == 0])

print("---------------")
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[1 2 3]
[2 4 6 8]
---------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr2)
print("---------------")

arr2[arr2 % 2 != 0] = 1 # replacing all odd numbers with 1

print(arr2)

[[1 2 1]
 [4 1 6]
 [1 8 1]]
---------------
[[1 2 1]
 [4 1 6]
 [1 8 1]]
