In [1]:
import numpy as np

diagonal_matrix = np.diag([6,3,1])
diagonal_matrix_2 = np.diag([6,3,1,4])

print(diagonal_matrix)
print(diagonal_matrix_2)

[[6 0 0]
 [0 3 0]
 [0 0 1]]
[[6 0 0 0]
 [0 3 0 0]
 [0 0 1 0]
 [0 0 0 4]]


In [ ]:
identity_matrix = np.eye(3,3)
print(identity_matrix)
print("-----------------")
print(np.eye(4,4))
print("___________________________")

# look at the diagon of thses 3 matrix
print(np.eye(3,4))
print("-----------------")
print(np.eye(3,4,1))
print("-----------------")
print(np.eye(3,4,-1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
___________________________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----------------
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [6]:
mat_A = np.array([
    [6,4,3],
    [1,2,7],
    [0,5,9]
])

print(mat_A)
print("--------------------")

print(mat_A.T) # mostly used in NumPy
print("--------------------")
print(np.linalg.matrix_transpose(mat_A))

[[6 4 3]
 [1 2 7]
 [0 5 9]]
--------------------
[[6 1 0]
 [4 2 5]
 [3 7 9]]
--------------------
[[6 1 0]
 [4 2 5]
 [3 7 9]]


In [7]:
print(np.linalg.inv(mat_A))

[[ 0.13821138  0.17073171 -0.17886179]
 [ 0.07317073 -0.43902439  0.31707317]
 [-0.04065041  0.24390244 -0.06504065]]
