In [ ]:
import numpy as np

arr = np.random.randint(1,100, size=(4,5)) # 10 rows, 5 cols

print(arr)

print(f"Shape : {arr.shape}")

b = arr.reshape(2,10) # must match total number of items (here, 20 and 20)
print(f"Shape : {b.shape}")

[[95 18 84 46 32]
 [13 93 62 11 75]
 [20 17 50 60 81]
 [63 48 14 56  2]]
Shape : (4, 5)
Shape : (2, 10)


In [ ]:
flattenArr = arr.flatten() # row-wise combined
print(flattenArr)

[95 18 84 46 32 13 93 62 11 75 20 17 50 60 81 63 48 14 56  2]


ravel()

In [ ]:
print(arr)
print("-------------------------")
colWiseFlatten = np.ravel(arr, order='F') # col wise flatten
rowWiseFlatten = np.ravel(arr, order='C') # row wise flatten

print(colWiseFlatten)
print(rowWiseFlatten)

[[95 18 84 46 32]
 [13 93 62 11 75]
 [20 17 50 60 81]
 [63 48 14 56  2]]
-------------------------
[95 13 20 63 18 93 17 48 84 62 50 14 46 11 60 56 32 75 81  2]
[95 18 84 46 32 13 93 62 11 75 20 17 50 60 81 63 48 14 56  2]


Array concatenate

In [14]:
a = np.random.randint(1,10, size=(3,4))
b = np.random.randint(20,30, size=(3,4))

print(a)
print(b)
print("------------------------------")

# row wise concatenate
row_merged = np.concatenate((a,b),axis=0)

print(row_merged)

print("------------------------------")

# col wise concatenate
col_merged = np.concatenate((a,b),axis=1)

print(col_merged)

[[7 8 9 2]
 [3 7 6 3]
 [7 5 7 2]]
[[21 20 29 22]
 [23 28 24 29]
 [22 29 24 20]]
------------------------------
[[ 7  8  9  2]
 [ 3  7  6  3]
 [ 7  5  7  2]
 [21 20 29 22]
 [23 28 24 29]
 [22 29 24 20]]
------------------------------
[[ 7  8  9  2 21 20 29 22]
 [ 3  7  6  3 23 28 24 29]
 [ 7  5  7  2 22 29 24 20]]


*row wise concatenate korar somoy column same thakte hobe* </br>
*column wise concatenate korar somoy row same thakte hobe*

**Transpose matrix**

In [16]:
a = np.random.randint(1,10, size=(3,4))

print(a)
print("'''''''''''''''''''")

transposeA = a.T
print(transposeA)

[[1 5 1 5]
 [8 9 2 7]
 [7 3 6 7]]
'''''''''''''''''''
[[1 8 7]
 [5 9 3]
 [1 2 6]
 [5 7 7]]


Array split

In [19]:
a = np.random.randint(1,10, size=(3,4))

print(a)
print("'''''''''''''''''''")
b = np.random.randint(1,10, size=(7,))

print(b)
print("'''''''''''''''''''")

splitted_arrayA = np.array_split(a,3)
print(splitted_arrayA)
print("'''''''''''''''''''")
splitted_arrayB = np.array_split(b,3)
print(splitted_arrayB)

[[6 3 1 6]
 [4 7 2 7]
 [7 1 5 8]]
'''''''''''''''''''
[7 6 4 3 9 5 3]
'''''''''''''''''''
[array([[6, 3, 1, 6]], dtype=int32), array([[4, 7, 2, 7]], dtype=int32), array([[7, 1, 5, 8]], dtype=int32)]
'''''''''''''''''''
[array([7, 6, 4], dtype=int32), array([3, 9], dtype=int32), array([5, 3], dtype=int32)]
