Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [2]:
import numpy as np

arr1 = np.array([1,32,3,64,7])
arr2 = np.array([
    [5,2,3,9],
    [6,1,3,4],
    [3,6,7,4]
])

arr3 = np.array([
    [
        [5,2,3,9],
        [6,4,3,4],
        [3,6,1,4]
    ],
    [
        [5,6,3,7],
        [1,4,3,4],
        [3,3,1,4]
    ],
    [
        [1,6,7,8],
        [1,6,2,4],
        [5,3,4,4]
    ]
])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

1
2
3
(5,)
(3, 4)
(3, 3, 4)


Create:
- an array of zeros of shape (3,3)</br>
- an array of ones of shape (2,5)</br>
- an array filled with 7</br>


In [4]:
arr_zeros = np.zeros((3,3))
print(arr_zeros)
print("++++++++++++++++")

arr_ones = np.ones((2,5))
print(arr_ones)
print("++++++++++++++++")

arr_seven = np.full((3,3),7)
print(arr_seven)
print("++++++++++++++++")

arr_inf = np.full_like(arr_zeros,np.inf)
print(arr_inf)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
++++++++++++++++
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
++++++++++++++++
[[7 7 7]
 [7 7 7]
 [7 7 7]]
++++++++++++++++
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


Create an array of even numbers between 10 and 50 using arange.

In [12]:
arr_evens = np.arange(10,51,2)
print(arr_evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 4×4 matrix from 0–15. Then , extract:
- the first row</br>
- the last column</br>
- a 2×2 subarray from the center</br>


In [28]:
matrix = np.arange(0,16,1).reshape(4,4)
print(matrix)
print("++++++++++++++++")

firstRow = matrix[0,:]
print(firstRow)
print("++++++++++++++++")

last_col = matrix[:,3:]
print(last_col)
print("++++++++++++++++")
last_col2 = matrix[:,3]
print(last_col2)

print("++++++++++++++++")

sub_arr = matrix[1:3,1:3]
print(sub_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
++++++++++++++++
[0 1 2 3]
++++++++++++++++
[[ 3]
 [ 7]
 [11]
 [15]]
++++++++++++++++
[ 3  7 11 15]
++++++++++++++++
[[ 5  6]
 [ 9 10]]


Create a 2D array with random integers, replace all values of 3rd column with 1

In [10]:
import numpy as np

mat = np.random.randint(1,20,(4,5))
print(mat)
print('-------------------')

# 3rd column
print(mat[:,2])
mat[:,2] = 0
print('_____________________')
print("3rd column replaced with 0")
print(mat)
print('------------------')
print(mat[:,2])

[[13 11 14 19 13]
 [ 2  7  4  5 11]
 [ 3 10 11  4  5]
 [16 14 10  8  6]]
-------------------
[14  4 11 10]
_____________________
3rd column replaced with 0
[[13 11  0 19 13]
 [ 2  7  0  5 11]
 [ 3 10  0  4  5]
 [16 14  0  8  6]]
------------------
[0 0 0 0]


In [ ]:
matD = np.random.randint(1,20,(3,3))
print(matD)
print("Diagonal values: ",np.diag(matD))
print('------------------')

np.fill_diagonal(matD,0)
print(matD)

[[ 8 14 12]
 [ 1 10  3]
 [19  4 15]]
Diagonal values:  [ 8 10 15]
------------------
[[ 0 14 12]
 [ 1  0  3]
 [19  4  0]]


### Slicing

a matrix of shape (6,6), get sub-matrix --> 3rd to 5th rows, 2nd to 4th cols

In [21]:
mat = np.random.randint(1,36,(6,6))
print(mat)
print('------------------')
print(mat[2:5,1:3])

[[ 2 32 29 27 19 16]
 [12 24 16  1 16 29]
 [ 3 26 33 11 26 27]
 [ 6 24 26 18 26 28]
 [10 13 14 31 21 29]
 [17  2  6 25 32 33]]
------------------
[[26 33]
 [24 26]
 [13 14]]


Row wise sum, column wise sum

In [25]:
mat = np.random.randint(1,6,(4,4))
print(mat)

print('Row wise sum: ')
print(np.sum(mat, axis=1))
print('======================')
print('Column wise sum: ')
print(np.sum(mat, axis=0))


[[3 1 5 4]
 [4 5 2 5]
 [2 4 1 3]
 [5 5 3 4]]
Row wise sum: 
[13 16 10 17]
Column wise sum: 
[14 15 11 16]


Reshape a matrix, if reshaping not possible, print "reshaping not possible"

In [ ]:
mat = np.random.randint(1,6,(3,4))
print(mat)
print('======================')

cur_shape = mat.shape
newShape = (4,3)

if(mat.size == newShape[0] * newShape[1]):
    new_mat = mat.reshape(newShape[0],newShape[1])
    print("After reshaping --> ",newShape)
    print(new_mat)
else:
    print("Reshaping not possible")

[[1 4 2 1]
 [5 2 3 5]
 [5 3 1 1]]
After reshaping -->  (4, 3)
[[1 4 2]
 [1 5 2]
 [3 5 5]
 [3 1 1]]


Scaler multiplication

In [33]:
mat = np.random.randint(1,6,(2,3))
print(mat)
print('======================')

new_mat = mat * 2

print(new_mat)

[[4 5 2]
 [2 1 4]]
[[ 8 10  4]
 [ 4  2  8]]


In [34]:
diag_mat = np.diag([2,3,4])

print(diag_mat)

[[2 0 0]
 [0 3 0]
 [0 0 4]]
