In [ ]:
import numpy as np
a = np.array([5,3,1,2,6,9])

index = np.where(a==2)

print(index) # (array([3]),)
print(index[0]) # [3]

if(np.where(a==2)[0].size > 0):
    print("Found")
else:
    print("Not found")

(array([3]),)
[3]
Found


In [ ]:
a = np.array([5,3,1,2,6,9])

index = np.where(a==2)

if(index[0].size > 0):
    print(f"Found at position {index[0]}")
else:
    print("Not found")

Found at position 3


In [20]:
a = np.array([5,3,1,2,6,9])

index = np.where(a==3)

if(index[0].size > 0):
    print(f"Found at position {index[0][0]}")
else:
    print("Not found")

Found at position 1


In [ ]:
a = np.array([5,3,1,2,6,9])

evens = np.where(a % 2 == 0); # returns index of matched items

print(evens)

(array([3, 4]),)


*np.where(condition,x,y) -- if condition matches, apply x, otherwise y*

In [22]:
a = np.array([5,3,1,2,6,9])

odd_to_zero = np.where(a % 2 == 0,a,0)
print(odd_to_zero)

[0 0 0 2 6 0]


In [ ]:
a = np.array([5,3,1,2,6,9])

p = np.where(a < 4,a,0) # if the value is less than 4, keep it as it is, otherwise replace with  0
print(p)

[0 3 1 2 0 0]


**Maximum, minimum -- index and value**

In [26]:
a = np.array([5,3,1,2,6,9])

max_val_idx = np.argmax(a)
min_val_idx = np.argmin(a)

print(max_val_idx)
print(min_val_idx)

print(f"Maximum value : {a[np.argmax(a)]}")
print(f"Minimum value: {a[np.argmin(a)]}")

5
2
Maximum value : 9
Minimum value: 1
