In [ ]:
import numpy as np

a = np.array([2,6,4,3,8,5])

# python sort
a.sort() # in-place sorting, modifies the original array

print(a) 

# how to preserve the original array
b = np.array([5,6,3,4,1,9])
x = b.copy()

x.sort()
print(f"x = {x}") # sorted

print(f"b = {b}") # unchanged, as we sorted the copied version

[2 3 4 5 6 8]
x = [1 3 4 5 6 9]
b = [5 6 3 4 1 9]


### NumPy sorting

In [4]:
a = np.array([3,6,4,1,8,5])

sorted_a = np.sort(a)
print(f"a = {a}")
print(f"sorted array = {sorted_a}")

a = [3 6 4 1 8 5]
sorted array = [1 3 4 5 6 8]


### 2D array sorting

*row wise sorting*

In [8]:
matrix = np.random.randint(1,10,(3,4))
print(matrix)

print("=======================")

row_wise_sorted = np.sort(matrix,axis = 1)

print(row_wise_sorted)

[[7 7 5 9]
 [4 6 9 6]
 [8 5 7 4]]
[[5 7 7 9]
 [4 6 6 9]
 [4 5 7 8]]


*column wise sorting*

In [9]:
matrix = np.random.randint(1,10,(3,4))
print(matrix)
print("=======================")

col_wise_sorted = np.sort(matrix,axis = 0)

print(col_wise_sorted)

[[6 1 3 5]
 [2 6 8 2]
 [5 1 8 8]]
[[2 1 3 2]
 [5 1 8 5]
 [6 6 8 8]]
