In [1]:
import numpy as np

# np.arange(start,end, step)
arr = np.arange(11,20,1)

print(arr)

[11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np

# np.arange(start,end, step)
arr = np.arange(11,20,2) # step 2

print(arr)

[11 13 15 17 19]


reshape the ranged ndarray using *reshape()*

In [ ]:
# reshape(shape of the matrix)

import numpy as np

arr = np.arange(1,13,1).reshape(3,4) # 3 rows, 4 colums, [step = 1]

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### np.linspace()

In [ ]:
import numpy as np

# np.linspace(start,end, koyta)
arr = np.linspace(1,10,10) # 1 to 10 , 10 ta

print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
import numpy as np

# np.linspace(start,end, koyta)
arr = np.linspace(1,10,5) # 1 to 10 , 5 ta

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np

# np.linspace(start,end(included), koyta)
arr = np.linspace(1,6,8) # 1 to 6 , 8 ta

print(arr)

[1.         1.71428571 2.42857143 3.14285714 3.85714286 4.57142857
 5.28571429 6.        ]


In [1]:
import numpy as np
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


### np.logsapce()

In [ ]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(1,3,3) # 1 to 3 , 3 ta--10^1, 10^2, 10^3

print(arr)

[  10.  100. 1000.]


In [ ]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(0,3,3) # 0 to 3 , 3 ta--10^0, 10^(something), 10^3

print(arr)

[   1.          31.6227766 1000.       ]


In [ ]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(1,4,5) # 1 to 4 , 5 ta--10^1, 10^(something from the range)....,10^4

print(arr)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]


With custom base, instead of default 10

In [ ]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(1,4,5, base=2) # 1 to 4 , 5 ta and base 2 -->> 2^1, 2^(something from the range)....,2^4

print(arr)

[ 2.          3.36358566  5.65685425  9.51365692 16.        ]


In [21]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(0,10,5, base=2) # 5 to 10 , 5 ta and base 2 -->> 2^5, 2^(something from the range)....,2^10

print(arr)

[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


In [ ]:
import numpy as np

# np.logspace(start,end(included), koyta)
# Default ==> 10^(numbers from the range provided)
arr = np.logspace(5,10,5, base=2) # 5 to 10 , 5 ta and base 2 -->> 2^5, 2^(something from the range)....,2^10

print(arr)

[  32.           76.10925536  181.01933598  430.53896461 1024.        ]
