In [4]:
import numpy as np

diagonal_matrix = np.diag([6,3,1])
diagonal_matrix_2 = np.diag([6,3,1,4])

print(diagonal_matrix)
print(diagonal_matrix_2)

[[6 0 0]
 [0 3 0]
 [0 0 1]]
[[6 0 0 0]
 [0 3 0 0]
 [0 0 1 0]
 [0 0 0 4]]


In [ ]:
identity_matrix = np.eye(3,3)
print(identity_matrix)
print("-----------------")
print(np.eye(4,4))
print("___________________________")

# look at the diagon of thses 3 matrix
print(np.eye(3,4))
print("-----------------")
print(np.eye(3,4,1))
print("-----------------")
print(np.eye(3,4,-1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
___________________________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----------------
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
