Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [4]:
import numpy as np

arr1 = np.array([1,32,3,64,7])
arr2 = np.array([
    [5,2,3,9],
    [6,1,3,4],
    [3,6,7,4]
])

arr3 = np.array([
    [
        [5,2,3,9],
        [6,4,3,4],
        [3,6,1,4]
    ],
    [
        [5,6,3,7],
        [1,4,3,4],
        [3,3,1,4]
    ],
    [
        [1,6,7,8],
        [1,6,2,4],
        [5,3,4,4]
    ]
])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

1
2
3
(5,)
(3, 4)
(3, 3, 4)


Create:
- an array of zeros of shape (3,3)</br>
- an array of ones of shape (2,5)</br>
- an array filled with 7</br>


In [ ]:
arr_zeros = np.zeros((3,3))
print(arr_zeros)

arr_ones = np.ones((2,5))
print(arr_ones)

arr_seven = np.full((3,3),7)
print(arr_seven)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Create an array of even numbers between 10 and 50 using arange.

In [12]:
arr_evens = np.arange(10,51,2)
print(arr_evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 4×4 matrix from 0–15. Then , extract:
- the first row</br>
- the last column</br>
- a 2×2 subarray from the center</br>


In [28]:
matrix = np.arange(0,16,1).reshape(4,4)
print(matrix)
print("++++++++++++++++")

firstRow = matrix[0,:]
print(firstRow)
print("++++++++++++++++")

last_col = matrix[:,3:]
print(last_col)
print("++++++++++++++++")
last_col2 = matrix[:,3]
print(last_col2)

print("++++++++++++++++")

sub_arr = matrix[1:3,1:3]
print(sub_arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
++++++++++++++++
[0 1 2 3]
++++++++++++++++
[[ 3]
 [ 7]
 [11]
 [15]]
++++++++++++++++
[ 3  7 11 15]
++++++++++++++++
[[ 5  6]
 [ 9 10]]
