### *Generate a 1D array with random values* 

In [ ]:
import numpy as np

# np.random.rand(size,)
arr = np.random.rand(3,) # 1D ndarray --> 3 items

print(arr)

[0.65480971 0.5662945  0.51762786]


### *Generate a 2D array with random values* 

In [ ]:
import numpy as np

# np.random.rand(shape)
arr = np.random.rand(3,4) # 2D --> 3 rows, 4 columns for each row
#values range from 0 to 1

print(arr)

[[0.40133296 0.79733465 0.57747341 0.68011868]
 [0.4793523  0.17781246 0.69312345 0.67606901]
 [0.846956   0.45574911 0.29071751 0.77607051]]


In [ ]:
import numpy as np
arr = np.random.rand(2,3) # 2D array- 2 rows and 3 colums of random values (0 to 1)
print(arr) 

[[0.3902377  0.09891694 0.07121367]
 [0.20079047 0.18240456 0.49330863]]


*Make a 2D array with int numbers*

In [ ]:
import numpy as np

# np.random.randint(start, end,(shape in a tuple))
arr = np.random.randint(1,10,(3,4)) # 2D --> 3 rows, 4 columns for each row
# values range from 1 to 9 (not 10)

print(arr)

[[5 3 3 9]
 [7 9 7 3]
 [7 5 5 8]]


In [ ]:
import numpy as np

# np.random.randint(start, end,(shape in a tuple))
arr = np.random.randint(1,100,(6,4)) # 2D --> 3 rows, 4 columns for each row
# values range from 1 to 99 (not 100)

print(arr)

[[35 72 37  1]
 [18 33 38 38]
 [92 96 91 90]
 [ 7 34 69 86]
 [ 9 11 50 61]
 [ 3 70 68 46]]


In [12]:
import numpy as np

# np.random.randint(start, end,(shape in a tuple))
arr = np.random.randint(1,50,(3,2,4)) # 2D --> 3 rows, 4 columns for each row
# values range from 1 to 99 (not 100)

print(arr)

[[[ 4 43  3 29]
  [38 29 20 35]]

 [[14 41 49 30]
  [16 48 27 24]]

 [[33 46 29 32]
  [29 30  5 13]]]


*Float numbers*

In [10]:
import numpy as np

# np.random.uniform(start, end,(shape in a tuple))
arr = np.random.uniform(50,100,(4,3)) # 2D --> 3 rows, 4 columns for each row
# values range from 50 to 99 (not 10)

print(arr)

[[78.63277834 62.24866329 73.50524248]
 [94.42742408 74.06866932 88.77717811]
 [90.58920123 64.7650894  57.8819542 ]
 [74.1163345  82.99793734 68.95310126]]
